#server port
server:
  port: 8082

#database configuration
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/student_course_microservice

# give application name
  application:
    name: COURSE-SERVICE



#NOTE:by-default fetch-registry and register-with-eureka are true for eureka client so, don't need to write

#connect client to discovery server that is with eureka server
#Note:Getting all instance registry info from the eureka server
#we fetch configuration from config server that's why we comment this config-code
#eureka:
  #instance:
    #prefer-ip-address: true
  #client:
    #fetch-registry: true
    #register-with-eureka: true
    #service-url:
      #defaultZone: http://localhost:8761/eureka

#fetch configuration from config server
  config:
    import: configserver:http://localhost:8085




#actuator configuration
management:
  endpoints:
    web:
      exposure:
        include: info,health
  info:
    env:
      enabled: true

#setting some information about to see when we hit info in actuator
info:
  app:
    name: Course-Service
    discription: this service is made from thapak deepak
    version: 1.0
