#server port
server:
  port: 8085

#application name
spring:
  application:
    name: MY-CONFIG-SERVER

#configuration to fetch MY-CONFIG-SERVER to GitHub
  cloud:
    config:
      server:
        git:
          uri: https://github.com/deepak948270/student-course-config-server
          clone-on-start: true




#connect client to discovery server that is with eureka server
#Note:Getting all instance registry info from the eureka server
#eureka:
  #client:
    #service-url:
      #defaultZone: http://localhost:8761/eureka/port




